# Numpy (NumericPy)
Matematik bilimindeki çoğu işlemi yapabilen hazır fonk. sahiptir.
Numerik işlemleri hızlı yapabilen bir kütüphane.


In [4]:
import numpy as np

In [5]:
np.__version__

'1.21.6'

# Numpy Dizileri (ndarray)
N-Dimensional Array

In [6]:
py_list = [1,2,3,4,5]
np_array = np.array([6,7,8,9,10])

py_list

[1, 2, 3, 4, 5]

In [7]:
np_array

array([ 6,  7,  8,  9, 10])

In [8]:
py_list2 = list(range(1_000_000))

In [9]:
%%timeit
[x+1 for x in py_list2]

34 ms ± 1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
np_array2 = np.array(py_list2)

In [13]:
%%timeit
np_array2 + 1

642 µs ± 80.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Numpy'da işlemler Vektörleştirilmiştir.
Döngü gerektirmeden vektörizasyon ile matematiksel işlemler yapar.

In [14]:
np_array3 = np_array + np_array2

ValueError: operands could not be broadcast together with shapes (5,) (1000000,) 

In [17]:
np_array2.shape

(1000000,)

In [18]:
np_array2

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [23]:
np_array3 = np.array([  [1,2,3], [4,5,6]  ])
np_array3

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np_array3.shape

(2, 3)

In [27]:
np_array4 = np.array(  [ [1,2,3], [3,4,5] ] )
np_array4.shape

(2, 3)

In [29]:
sum_arrays = np_array3 + np_array4
sum_arrays

array([[ 2,  4,  6],
       [ 7,  9, 11]])

In [30]:
np_array5 = np.array([  [2,1], [5,3], [6,8]   ])
np_array5.shape

(3, 2)

In [31]:
sum_arrays2 = np_array3+np_array5

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [38]:
np_array3

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np_array6 = np.array([10,20,30])
np_array6.shape

(3,)

In [37]:
np_array3+np_array6

array([[11, 22, 33],
       [14, 25, 36]])

In [39]:
np_array4.shape

(2, 3)

In [40]:
np_array5.shape

(3, 2)

# Reshape işlemi

In [41]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [42]:
arr.shape

(6,)

In [47]:
reshaped_arr = arr.reshape(3, 2)
reshaped_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
reshaped_arr.shape

(3, 2)

In [49]:
arr2 = np.array([ [1,2,3], [4,5,6] ])
arr2.shape

(2, 3)

In [53]:
flattened_arr = arr2.reshape(-1)
flattened_arr

array([1, 2, 3, 4, 5, 6])

# Tensors

In [58]:
tensor_arr = np.array(      

    [   
        [ [1, 2, 3], [3, 4,5] ],
        [ [4, 5,6], [6,7,8] ],
        [ [4, 5,6], [6,7,8] ],
        [ [4, 5,6], [6,7,8] ],
    ]

)
tensor_arr

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [6, 7, 8]],

       [[4, 5, 6],
        [6, 7, 8]],

       [[4, 5, 6],
        [6, 7, 8]]])

In [59]:
tensor_arr.shape

(4, 2, 3)

In [60]:
np.ndim(tensor_arr)

3

In [61]:
np.ndim(arr2)

2

In [62]:
np.ndim(arr)

1

In [63]:
arr

array([1, 2, 3, 4, 5, 6])

In [64]:
arr.T

array([1, 2, 3, 4, 5, 6])

In [71]:
arr2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
vector_2D = np.array([ [1,2,3] ])
vector_2D.shape

(1, 3)

In [70]:
vector_2D.T.shape

(3, 1)